#!/usr/bin/env python

import os,sys,glob,tempfile

srcdir = os.getenv("srcdir")
builddir = os.getcwd()
execfile = "env LANG=ko_KR.UTF-8 python %s/../scripts/ko-po-check" % builddir
os.chdir(srcdir)
testfiles = glob.glob("test-[0-9]*.po")

testfiles.sort()

ret = 0
for file in testfiles:
    print "Checking %s..." % file
    tfn = tempfile.mktemp()
    print "%s --moduledir=%s/.. --checksdir=%s/../checks %s > %s" % (execfile, srcdir, srcdir, file, tfn)
    os.system("%s --moduledir=%s/.. --checksdir=%s/../checks %s | sort > %s" %
                  (execfile, srcdir, srcdir, file, tfn))
    if (os.system("diff -u -2 %s %s" % (file[:-3]+".out", tfn)) != 0):
        os.unlink(tfn)
	ret = 1
    else:
        os.unlink(tfn)

sys.exit(ret)
